#!/bin/bash
# Install golint if not already present, assumes `go` command is present.
type golint > /dev/null 2>&1 || go get -u github.com/golang/lint/golint && export PATH="$GOPATH/bin:$PATH"

confidence="1.0" # Set the confidence as high as possible, to avoid false-positives.
out=$(golint -min_confidence $confidence ./... | grep -v "pb.go") # Avoid go files generated by protoc.

if [[ ! -z "$out" ]]; then
    echo "$out"
    exit 1
fi
